# Generated by Django 5.2.7 on 2025-10-30 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voter_analytics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='address_apt_number',
            field=models.TextField(blank=True),
        ),
    ]
