# Generated by Django 5.2.6 on 2025-10-21 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hw', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='image_file',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='comment',
            name='image_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='reply',
            name='image_file',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='reply',
            name='image_url',
            field=models.URLField(blank=True),
        ),
    ]
