# Generated by Django 5.2.7 on 2025-11-04 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hw', '0004_comment_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='username',
        ),
        migrations.RemoveField(
            model_name='reply',
            name='username',
        ),
    ]
