# Generated by Django 5.2.7 on 2025-11-04 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hw', '0005_remove_comment_username_remove_reply_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('age', models.IntegerField()),
                ('gender', models.TextField()),
                ('hours_online', models.FloatField()),
            ],
        ),
    ]
