# Generated by Django 5.2.6 on 2025-12-08 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_customer_created_at_dependent_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saleitem',
            name='description',
        ),
    ]
