# Generated by Django 5.2.6 on 2025-12-08 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_customer_guardian_customer_is_dependent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleitem',
            name='name',
            field=models.CharField(default='item', max_length=128),
            preserve_default=False,
        ),
    ]
