# Generated by Django 5.2.6 on 2025-12-08 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_saleitem_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saleitem',
            name='item',
        ),
    ]
