# Generated by Django 5.2.6 on 2025-12-08 19:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_remove_saleitem_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleitem',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='project.item'),
        ),
    ]
