# Generated by Django 5.2.6 on 2025-12-09 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0009_saleitem_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleitem',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='project.customer'),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='needs_customer',
            field=models.BooleanField(default=False),
        ),
    ]
