# Generated by Django 5.2.6 on 2025-12-09 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0010_saleitem_customer_saleitem_needs_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saleitem',
            name='needs_customer',
        ),
        migrations.AddField(
            model_name='item',
            name='needs_customer',
            field=models.BooleanField(default=False),
        ),
    ]
